### ISSUE TITLE
Generating a new tornadofx gradle project doesn't configure the project properly with Gradle

### ISSUE THREAD

**Issue by jtietema** [edvin/tornadofx-idea-plugin#13]
When generating a new tornadofx gradle project it doesn't seem that the intellij project config knows that it is a gradle project. The pane on the right shows a maven pane instead of Gradle project pane.

Also the `gradlew` file seems to be incorrect. It has a `\` character in front of all the `#` and `$` characters and is not executable.

**Comment by edvin** [comment]
Ah, it seems like some of the artifacts, like the gradle wrapper is beeing escaped. I'll look into it later to day. Thanks for reporting :)

**Comment by edvin** [comment]
I tried disabling the variable interpolation when building the project template, to no avail. This seems like a bug in the template bundling mechanism of IDEA. I will file a bug report for it.

**Comment by edvin** [comment]
I've filed an issue for this:

https://youtrack.jetbrains.com/issue/IDEA-166037

**Comment by nakamin** [comment]
It seems like the problem occurs when creating the jar. If you look at the gradlew in the jar, it is already messed up...

**Comment by edvin** [comment]
I'm going to remove the old project templates and generate a new project wizard that let's you choose buld system etc, and generate the project structure instead of relying on these templates. There are some issues with the template parsing for gradle build files, so I'l divert resources to the project wizard instead of trying to solve this :)

**Comment by edvin** [comment]
This should be fixed in plugin version 1.7.7 which was released today :)
