### ISSUE TITLE
Error:Unable to make the module: tornadofx-gradle-project_main, related gradle configuration was not found. Please, re-import the Gradle project and try again.

### ISSUE THREAD

**Issue by defp** [edvin/tornadofx-idea-plugin#15]
IDEA create project and can not build

`Error:Unable to make the module: tornadofx-gradle-project_main, related gradle configuration was not found. Please, re-import the Gradle project and try again.`

![image](https://cloud.githubusercontent.com/assets/612381/21563956/66d6ca74-cec2-11e6-97f9-96d5b7ca7483.png)
 
![image](https://cloud.githubusercontent.com/assets/612381/21563980/adff4f70-cec2-11e6-9bbc-14d9c4f3c3c7.png)

**Comment by edvin** [comment]
I think this is due to that the IDEA project template creation tool doesn't fully support Gradle, so it leaves some artifacts that should have been removed. When you open the project the first time it should ask you do remove the dead modules (tornadofx-gradle-project_main and _test) and accept your new (hellotornadofx). If that doesn't work, try closing the project and removing the .idea folder and open it again.

There is also a bug in IDEA causing the gradle wrapper to be broken upon import, I've filed an issue with JetBrains. See also this for more info:

https://github.com/edvin/tornadofx-idea-plugin/issues/13
